### ISSUE TITLE
not recognized as 1.19 (fabric)

### ISSUE THREAD

**Issue by AnomalousDeity** [AbsolemJackdaw/FixMySpawnR#1]
when installed minecraft does not load and opens a error of incompatible mod set, saying "replace Example mod (modid) 1.1.0 with any version compatible with minecraft 1.19"
"mod 'example mod' (modid) 1.1.0 requires any 1.18.x version of minecraft (minecraft), but only the wrong version is present: 1.19!"

I do not have a Mod by the name of 'example mod' and this only occurs when loading the mod up (i have the dependencies installed)
when i remove it, works fine.

**Comment by AbsolemJackdaw** [comment]
Looks like I forgot to upload the fix. it was fixed a couple days ago, and I did upload forge 1.1.1, but forgot to upload fabric 1.1.1 in the process.... 
It should be accepted in a minute and ready for you to download ! 
https://www.curseforge.com/minecraft/mc-mods/fixmyspawnr/files/3856269

So sorry for the delay. thank you for bringing it to my attention !
